create type grocery as ENUM ('Main', 'Snack', 'Lunch', 'Breakfast');

create table if not exists shopping_list (
    id integer primary key generated by default as identity,
    name text not null,
    price numeric(8, 3),
    date_added timestamp default now() not null,
    checked boolean default false,
    price grocery
);